title: "rap-and-metal"
main_genres:
  - "Rock"
  - "Rap"
  - "R&B" #sometimes rap albums show up as this
sub_genres:
  fuzzy_matches:
    - "Metal"
    - "Grindcore"
    - "Hardcore"
    - "Rap"
    - "Virtuoso"
  exact_matches:
    - "Grunge" #because we don't want to match "Post-Grunge"